### ISSUE TITLE
Anti-virus force closes the game and deletes the Sneaksters.exe file

### ISSUE THREAD

**Issue by thomasdowding** [Meorge/sneaksters-testing#82] opened 2019-12-30 13:06 UTC
As discovered by RedStoneMatt, Avast anti-virus will delete the Sneaksters.exe file shortly after the Zenith Point logo, forcing the game to close. This might happen with other anti-virus software as well.

This is probably something that can't be fixed as it is caused by third party software. A disclaimer somewhere saying that this can happen with anti-virus software might be needed if it doesn't already exist. I assume this will only be an issue with development builds anyway and when the game is officially released the platform it is released on will have "anti-virus whitelisting" preventing this from happening.

**Comment by Meorge** [comment] 2019-12-30 17:25
Duplicate of issue #38

**Closed by Meorge** 2019-12-30 17:25 UTC
Labels: duplicate
