### ISSUE TITLE
The game deletes itself because of Avast

### ISSUE THREAD

**Issue by RedStoneMatt** [Meorge/sneaksters-testing#81] opened 2019-12-30 13:03 UTC
When Avast is activated, there's like 50% chance for the Sneaksters.exe file to delete itself after launching it.

**Comment by Meorge** [comment] 2019-12-30 17:25
Duplicate of issue [#38](https://github.com/Meorge/sneaksters-testing/issues/38)

**Closed by Meorge** 2019-12-30 17:25 UTC
Labels: duplicate
